class_name ArcadeLocalization
extends RefCounted

const UI := {
	"en": {
		"title_start": "TAP / ENTER TO START",
		"title_links": "HIGH SCORES                         OPTIONS",
		"high_scores": "LOCAL HIGH SCORES",
		"return": "TAP / ENTER TO RETURN",
		"options": "OPTIONS",
		"paused_options": "PAUSED // OPTIONS",
		"resume": "ENTER / PAUSE TO RESUME",
		"option_hint": "UP/DOWN SELECT   LEFT/RIGHT CHANGE   TAP SIDES",
		"music_volume": "MUSIC VOLUME",
		"sfx_volume": "EFFECTS VOLUME",
		"touch_scale": "TOUCH SIZE",
		"touch_layout": "TOUCH LAYOUT",
		"ui_scale": "UI SIZE",
		"screen_shake": "SCREEN SHAKE",
		"hit_flash": "HIT FLASH",
		"haptics": "HAPTICS",
		"high_contrast_cues": "HIGH-CONTRAST CUES",
		"subtitles": "SUBTITLES",
		"language": "LANGUAGE",
		"controls": "REMAP CONTROLS",
		"controls_title": "REMAP CONTROLS",
		"open": "OPEN  >",
		"score_columns": "RANK   OPERATIVE       SCORE       STAGE / TEAM",
		"rebind_hint": "ATTACK TO REBIND     ESC CANCELS CAPTURE",
		"press_key": "PRESS A KEY...",
		"move_left": "MOVE LEFT",
		"move_right": "MOVE RIGHT",
		"move_up": "MOVE UP",
		"move_down": "MOVE DOWN",
		"attack": "ATTACK",
		"jump": "JUMP",
		"special": "SPECIAL",
		"pause": "PAUSE",
		"continue": "CONTINUE?",
		"continue_hint": "ATTACK / START TO CONTINUE",
		"game_over": "GAME OVER",
		"final_score": "FINAL SCORE",
		"on": "ON",
		"off": "OFF",
		"layout_classic": "CLASSIC",
		"layout_compact": "COMPACT",
		"layout_left_handed": "LEFT HANDED",
	},
	"zh": {
		"title_start": "点击 / 回车 开始",
		"title_links": "高分榜                              设置",
		"high_scores": "本地高分榜",
		"return": "点击 / 回车 返回",
		"options": "设置",
		"paused_options": "暂停 // 设置",
		"resume": "回车 / 暂停键 继续",
		"option_hint": "上下选择   左右调整   触屏点击两侧",
		"music_volume": "音乐音量",
		"sfx_volume": "音效音量",
		"touch_scale": "触控尺寸",
		"touch_layout": "触控布局",
		"ui_scale": "界面字号",
		"screen_shake": "画面震动",
		"hit_flash": "受击闪光",
		"haptics": "触觉反馈",
		"high_contrast_cues": "高对比度警告",
		"subtitles": "字幕",
		"language": "语言",
		"controls": "按键重绑定",
		"controls_title": "按键重绑定",
		"open": "打开  >",
		"score_columns": "排名   角色             得分        关卡 / 队伍",
		"rebind_hint": "按攻击键重绑定     ESC 取消输入",
		"press_key": "请按一个按键...",
		"move_left": "向左移动",
		"move_right": "向右移动",
		"move_up": "向上移动",
		"move_down": "向下移动",
		"attack": "攻击",
		"jump": "跳跃",
		"special": "必杀技",
		"pause": "暂停",
		"continue": "是否续关？",
		"continue_hint": "攻击 / 开始键 确认续关",
		"game_over": "游戏结束",
		"final_score": "最终得分",
		"on": "开启",
		"off": "关闭",
		"layout_classic": "经典",
		"layout_compact": "紧凑",
		"layout_left_handed": "左手",
	},
}

const DIALOGUE_ZH := {
	"This district answers to me.": "这片街区由我说了算。",
	"No more warnings. Overdrive!": "警告结束。超载启动！",
	"The flood keeps what it takes.": "洪水夺走的，从不归还。",
	"Then run against the current!": "那就逆着激流逃吧！",
	"Everything breaks in the deluge!": "洪流之中，一切都会粉碎！",
	"This road belongs to the convoy.": "这条路属于我们的车队。",
	"Watch the asphalt burn.": "看着柏油路燃烧吧。",
	"Redline. No brakes.": "转速拉满。绝不刹车。",
	"Every road ends in my furnace.": "每一条路最终都通向我的熔炉。",
	"Steel answers when I call.": "钢铁会回应我的召唤。",
	"Overdrive. Melt with the rest!": "超载启动。和他们一起熔化吧！",
	"The refuge burns by my command.": "避难所因我的命令而燃烧。",
	"Then face what survived the furnace.": "那就面对从熔炉中活下来的东西。",
	"Ash and water. Drown in both!": "灰烬与洪水——溺死其中吧！",
	"This quarry was old before your species learned fear.": "在你们的种族懂得恐惧前，这座矿场就已存在。",
	"Wake, old giant. Clear the shaft.": "醒来吧，古老巨兽。清空矿井。",
	"Then I drill through you myself!": "那我就亲自把你钻穿！",
	"The lower archive remains sealed.": "下层档案库必须继续封锁。",
	"Nyx. Lockstep pattern. No gaps.": "妮克斯，同步阵型，不留缺口。",
	"You crossed six locks to die at the seventh.": "你穿过六道锁，只为死在第七道。",
	"Crossfire live. Close every lane.": "交叉火力启动。封死所有通道。",
	"You crossed seven locks to witness a new world.": "你穿过七道锁，只为见证新世界。",
	"Then survive the shape it demands.": "那就从它要求的形态中活下来。",
	"No vessel. No limit. No retreat.": "无须容器。没有极限。绝不后退。",
}

# Player-visible authored content stays in its original data resources. This
# catalog translates those stable display strings without duplicating stage or
# encounter structures per locale.
const CONTENT_ZH := {
	# Shell and HUD.
	"ARCADE SURVIVAL": "街机生存战",
	"HI  %08d": "最高  %08d",
	"AN ORIGINAL CLEAN-ROOM ARCADE CAMPAIGN": "原创净室街机战役",
	"SELECT OPERATIVE": "选择行动队员",
	"FOUR ROLES // ONE MISSION": "四种定位 // 同一使命",
	"TAP A CARD TWICE TO DEPLOY": "连续点击角色卡两次出击",
	"EACH PLAYER CHOOSES     A / START  READY     BACK  CANCEL": "每位玩家选择角色     A / 开始键 准备     返回键 取消",
	"AREA %d/%d": "区域 %d/%d",
	"HOSTILES  %02d": "敌人  %02d",
	"ADVANCE  →": "前进  →",
	"COMBAT ZONE LOCKED": "战斗区域已封锁",
	"ROUTE OPEN": "路线已开放",
	"DANGER": "危险",
	"MOVE WASD/ARROWS   ATTACK J/Z   JUMP K/X   COMMAND DOWN>FORWARD+ATTACK   SPECIAL ATTACK+JUMP": "移动 WASD/方向键   攻击 J/Z   跳跃 K/X   指令 下>前+攻击   必杀 攻击+跳跃",
	"%s  // PHASE %d": "%s  // 阶段 %d",
	"STAGE %d READY": "第 %d 关 准备",
	"STAGE %d": "第 %d 关",
	"PLAYER %d JOINED": "玩家 %d 已加入",
	"CONTROLLER DISCONNECTED": "控制器连接已断开",
	"PLAYER %d RESERVED": "已为玩家 %d 保留位置",
	"CONTROLLER RECONNECTED": "控制器已重新连接",
	"PLAYER %d RESTORED": "玩家 %d 已恢复",
	"TEAM ATTACK!": "团队攻击！",
	"%s LINK // %d TARGETS": "%s 联携 // %d 个目标",
	"AREA CLEAR": "区域已清理",
	"KEEP MOVING RIGHT  →": "继续向右前进  →",
	"PLAYER %d DOWN": "玩家 %d 倒地",
	"MOVE CLOSE + ATTACK TO REVIVE": "靠近队友并按攻击键救援",
	"PLAYER %d REVIVED": "玩家 %d 已获救",
	"35% HEALTH + TEMPORARY INVINCIBILITY": "恢复 35% 生命 + 短暂无敌",
	"PLAYER %d OUT": "玩家 %d 退场",
	"NO CONTINUES REMAIN": "续关次数已用尽",
	"PLAYER %d CONTINUE!": "玩家 %d 续关！",
	"TEMPORARY INVINCIBILITY": "短暂无敌",
	"CONTINUE TIME EXPIRED": "续关时间已结束",
	"STAGE %d CLEAR": "第 %d 关完成",
	"TIME BONUS": "时间奖励",
	"LIFE BONUS": "生命奖励",
	"CLEAR BONUS": "通关奖励",
	"TAP / ENTER FOR ROUTE MAP": "点击 / 回车 查看路线图",
	"TAP / ENTER FOR CAMPAIGN REPORT": "点击 / 回车 查看战役报告",
	"THE GENESIS CORE IS SILENT": "创生核心归于沉寂",
	"THE LOCKDOWN BREAKS. THE CAPTIVE WILDLANDS ARE FREE.": "封锁已经瓦解，被囚禁的荒野重获自由。",
	"ABOVE THE MOUNTAIN, THE FIRST CLEAN DAWN RETURNS.": "群山之上，久违的澄澈黎明再次升起。",
	"OPERATIVES RETURNED  %d     FINAL SCORE  %08d": "归队队员  %d     最终得分  %08d",
	"TAP / ENTER FOR CREDITS": "点击 / 回车 查看制作名单",
	"GAME DESIGN & DIRECTION": "游戏设计与指导",
	"WILDLAND STRIKE TEAM": "荒野突击队团队",
	"ENGINE & TOOLS": "引擎与工具",
	"GODOT ENGINE": "Godot 引擎",
	"ORIGINAL ART & AUDIO": "原创美术与音频",
	"CLEAN-ROOM PRODUCTION": "净室制作",
	"COMBAT / CAMPAIGN / MOBILE": "战斗 / 战役 / 移动端",
	"PROJECT CONTRIBUTORS": "项目贡献者",
	"QUALITY ASSURANCE": "质量保证",
	"DETERMINISTIC + WEB + iOS": "确定性测试 + 网页 + iOS",
	"THANK YOU FOR PLAYING  //  %08d": "感谢游玩  //  %08d",
	"TAP / ENTER FOR FINAL REPORT": "点击 / 回车 查看最终报告",
	"CAMPAIGN COMPLETE": "战役完成",
	"%d-STAGE WILDLAND FRONT SECURED": "荒野战线共 %d 关，现已全部确保",
	"FRONT COMPLETION BONUS": "全战线完成奖励",
	"REMAINING CONTINUES": "剩余续关次数",
	"FINAL SCORE": "最终得分",
	"LOCAL RANK  #%02d": "本地排名  #%02d",
	"TAP / ENTER TO RETURN TO TITLE": "点击 / 回车 返回标题画面",
	"TAP / ENTER TO RESTART": "点击 / 回车 重新开始",
	"HOW TO SURVIVE THE WILDLANDS": "荒野生存指南",
	"MOVE": "移动",
	"EIGHT DIRECTIONS // DOUBLE TAP TO RUN": "八方向移动 // 双击方向奔跑",
	"STRIKE": "打击",
	"FOUR-HIT CHAIN // RUN + AIR ATTACKS": "四连击 // 奔跑与空中攻击",
	"GRAPPLE": "擒拿",
	"CLOSE ATTACK // STRIKE OR THROW": "贴身攻击 // 连打或投掷",
	"SPECIAL": "必杀",
	"ATTACK + JUMP // COSTS HEALTH ON HIT": "攻击+跳跃 // 命中后消耗生命",
	"CO-OP": "合作",
	"REVIVE ALLIES // LINK SPECIALS": "救援队友 // 联携必杀",
	"8 STAGES  //  4 OPERATIVES  //  1–3 LOCAL PLAYERS": "8 个关卡  //  4 名队员  //  1–3 人本地合作",
	"TAP / ENTER TO JOIN": "点击 / 回车 加入",
	"WILDLAND CAMPAIGN ROUTE": "荒野战役路线",
	"ACTIVE FRONT // %d OPERATIONS": "当前战线 // %d 项行动",
	"CLEARED": "已完成",
	"NEXT  STAGE %d // %s": "下一关  第 %d 关 // %s",
	"THREAT %.2fx   CLEAR %05d   SCORE %08d   CONTINUES %d": "威胁 %.2fx   通关 %05d   得分 %08d   续关 %d",
	"TAP / ENTER TO DEPLOY": "点击 / 回车 出击",
	"OUT": "退场",
	"DOWN %.1f": "倒地 %.1f",
	"DOWN": "倒地",
	"READY": "准备完成",
	"SELECTING": "选择中",
	"VIT": "生命",
	"SPD": "速度",
	"PWR": "力量",
	"TECH": "技巧",
	"CMD": "指令技",
	"%s // 24-FRAME ACTION GRID": "%s // 24 帧动作表",
	"IDLE / MOVE / COMBAT / AIR / DAMAGE / WEAPON / VICTORY": "待机 / 移动 / 战斗 / 空中 / 受伤 / 武器 / 胜利",

	# Heroes, bosses, weapons, and rewards.
	"RANGER": "游骑兵",
	"MARA": "玛拉",
	"KESTREL": "红隼",
	"ATLAS": "阿特拉斯",
	"BALANCED VANGUARD": "均衡先锋",
	"FIELD TECHNICIAN": "战地技师",
	"AERIAL SCOUT": "空中斥候",
	"POWER GRAPPLER": "力量擒拿手",
	"BREAKER RUSH": "破阵冲锋",
	"GUARD SWEEP": "护身横扫",
	"ARC SNARE": "电弧禁锢",
	"OVERLOAD FIELD": "过载力场",
	"GALE LANCE": "疾风突刺",
	"CROSSWIND": "交错旋风",
	"FAULTLINE DRIVE": "断层冲击",
	"GROUNDBREAKER": "裂地震击",
	"WARDEN ROURKE": "守望者·鲁尔克",
	"COMMANDER VOSS": "指挥官·沃斯",
	"ACCESSIBILITY": "无障碍功能",
	"MIREWARDEN SABLE": "沼泽守卫·塞布尔",
	"IRON VULTURE": "钢铁秃鹫",
	"FORGE REGENT VOLKR": "铸炉摄政·沃尔克",
	"CINDER MATRIARCH VEYRA": "烬火主母·薇拉",
	"TITAN WARDEN KORVA": "泰坦守卫·科尔瓦",
	"VAULT SENTINELS ORIN & NYX": "地库哨兵·奥林与妮克斯",
	"VAULT SENTINEL ORIN": "地库哨兵·奥林",
	"VAULT SENTINEL NYX": "地库哨兵·妮克斯",
	"ARCHITECT SERA CALDER": "架构师·塞拉·考尔德",
	"GENESIS CORE": "创生核心",
	"MACHETE": "砍刀",
	"GRENADE": "手榴弹",
	"PISTOL": "手枪",
	"STEEL PIPE": "钢管",
	"SHOTGUN": "霰弹枪",
	"BURST SMG": "连发冲锋枪",
	"RIFLE": "步枪",
	"ROCKET": "火箭筒",
	"MOLOTOV": "燃烧瓶",
	"PROX MINE": "感应地雷",
	"DESERT INTERCEPTOR": "荒漠拦截车",
	"SHOCK BATON": "电击棍",
	"FIELD WHIP": "战地长鞭",
	"SNACK": "零食",
	"RATION": "口粮",
	"FIELD MEAL": "战地餐",
	"FEAST": "盛宴",
	"TOKEN": "代币",
	"BADGE": "徽章",
	"INTEL": "情报",
	"RELIC": "遗物",

	# Stage names, scenes, routes, and clear messages.
	"THE RUINED DISTRICT": "荒废城区",
	"CITY BREACH": "城市突破",
	"THE FIRST FRONT HAS FALLEN": "第一道战线已经攻破",
	"RUINED AVENUE": "荒废大道",
	"FLOODED COURTYARD": "积水庭院",
	"PROCESSING PLANT": "加工厂",
	"THE CITY HAS GONE WILD": "整座城市已经失控",
	"WATCH THE ROLLING DRUM": "小心滚动铁桶",
	"THE BLOCKADE IS AHEAD": "封锁线就在前方",
	"THE FLOODED WILDERNESS": "洪水荒野",
	"MONSOON FRONT": "季风前线",
	"THE SPILLWAY ROUTE IS OPEN": "泄洪道路线已经打通",
	"CYPRESS FLOODPLAIN": "柏树林漫滩",
	"DROWNED RESEARCH CAMP": "被淹研究营地",
	"ANCIENT SPILLWAY": "远古泄洪道",
	"THE STORM HAS ERASED THE ROAD": "暴风雨抹去了道路",
	"SIGNAL FIRES STILL BURN": "信号火仍在燃烧",
	"THE FLOODGATE IS AHEAD": "闸门就在前方",
	"HIGHWAY OF TEETH": "獠牙公路",
	"ARMORED PURSUIT": "装甲追击",
	"THE CONVOY CORRIDOR IS OURS": "车队走廊已被掌控",
	"CANYON INTERCEPT": "峡谷截击",
	"CONVOY CHECKPOINT": "车队检查站",
	"TEMPEST OVERPASS": "风暴高架桥",
	"TAKE THE INTERCEPTOR AND RUN THEM DOWN": "驾驶拦截车追上并撞毁他们",
	"BREAK THE BLOCKADE AT FULL SPEED": "全速冲破封锁",
	"THE IRON VULTURE IS CLOSING FAST": "钢铁秃鹫正在高速逼近",
	"THE IRON FOUNDRY": "钢铁铸造厂",
	"FOUNDRY ASSAULT": "铸造厂突击",
	"THE PROCESSING PLANT IS SECURE": "加工厂已经确保",
	"ARMORED MOTOR POOL": "装甲车辆场",
	"ARMORED ASSEMBLY LINE": "装甲装配线",
	"CRUCIBLE LIFT": "熔炉升降台",
	"THE CONVOY'S FOUNDRY IS STILL RUNNING": "车队的铸造厂仍在运转",
	"THE MACHINES DO NOT STOP FOR INTRUDERS": "机器不会为入侵者停下",
	"VOLKR IS WAITING ABOVE THE FURNACE": "沃尔克正在熔炉上方等待",
	"THE BURNING SETTLEMENT": "燃烧聚落",
	"FIRESTORM EVACUATION": "火风暴撤离行动",
	"THE SETTLEMENT STILL STANDS": "聚落仍然屹立",
	"EMBER REFUGE": "余烬避难所",
	"BURNING MARKET": "燃烧集市",
	"ASHEN CISTERN": "灰烬蓄水池",
	"THE EVACUATION ROUTE IS COLLAPSING": "撤离路线正在崩塌",
	"FIRE AND SMOKE ARE CUTTING OFF THE ROUTE": "火焰与浓烟正在切断路线",
	"VEYRA IS WAITING ABOVE THE WATERWORKS": "薇拉正在水利设施上方等待",
	"THE TITAN QUARRY": "泰坦采石场",
	"JUNGLE DEEP-CORE MINE": "丛林深核矿场",
	"THE TITAN SHAFT IS SILENT": "泰坦矿井已经沉寂",
	"JADE RESEARCH TRAIL": "翠玉研究小径",
	"JUNGLE MINE ENTRANCE": "丛林矿场入口",
	"TITAN SHAFT": "泰坦矿井",
	"THE OLD EXPEDITION ROUTE IS ALIVE": "旧探险路线重新活跃",
	"THE ORE RAILS STILL HAVE POWER": "矿轨仍然通电",
	"SOMETHING ENORMOUS IS ABOVE THE QUARRY": "采石场上方有某个庞然大物",
	"THE SEVENTH LOCK": "第七道锁",
	"DESCENT TO THE TWIN CORE": "下潜至双核区",
	"THE LOWER ARCHIVE IS OPEN": "下层档案库已经开放",
	"DESCENT ELEVATOR": "下行升降梯",
	"CRYOGENIC ARCHIVE": "低温档案库",
	"TWIN CORE VAULT": "双核地库",
	"THE VAULT IS TWO KILOMETERS BELOW": "地库位于地下两公里",
	"SECURITY GRID HAS GONE LIVE": "安防网格已经启动",
	"TWO SENTINELS HOLD THE FINAL LOCK": "两名哨兵守卫着最后一道锁",
	"THE GENESIS PROTOCOL": "创生协议",
	"FINAL GENE-FORGE ASSAULT": "基因熔炉最终突击",
	"THE WILDLANDS ARE FREE": "荒野重获自由",
	"GENE-FORGE CAUSEWAY": "基因熔炉通道",
	"SPECIMEN GALLERY": "样本陈列馆",
	"THE GENESIS CORE": "创生核心",
	"THE QUARANTINE GATES ARE CLOSING": "隔离闸门正在关闭",
	"CONTAINMENT IS FAILING": "收容系统正在失效",
	"FINAL LOCKDOWN // NO RETURN": "最终封锁 // 无法回头",

	# Encounter cards and instructions.
	"FIGHT!": "战斗！",
	"DEFEAT THEM ALL TO ADVANCE": "击败所有敌人后继续前进",
	"DANGER!": "危险！",
	"BREAK THE GATE": "击破大门",
	"BREAK THE BLOCKADE": "突破封锁线",
	"MARSH AMBUSH": "沼泽伏击",
	"CAMP UNDER SIEGE": "营地围攻",
	"THE FLOODGATE": "泄洪闸门",
	"ANCIENT TERRITORY": "远古领地",
	"USE THE CURRENT TO BREAK THEIR LINE": "利用水流冲破敌阵",
	"THE WILDLIFE IS NOT ON THEIR SIDE": "野生生物并不站在他们一边",
	"MIREWARDEN SABLE CONTROLS THE CURRENT": "沼泽守卫塞布尔控制着水流",
	"WAKE THE HERD AT YOUR OWN RISK": "惊醒兽群，后果自负",
	"ACCELERATE, STEER, AND RAM": "加速、转向并撞击",
	"CHANGE LANES THROUGH THE BLOCKADE": "变换车道穿越封锁",
	"KEEP THE INTERCEPTOR IN ONE PIECE": "保持拦截车完整",
	"MOUNTED FIRE HAS INFINITE BELTS": "车载火力拥有无限弹链",
	"DODGE THE MINES — BREAK THE RAM": "躲避地雷——摧毁撞角",
	"RED MESA HIGHWAY": "赤岩公路",
	"CONVOY COUNTERATTACK": "车队反击",
	"TEMPEST PURSUIT": "风暴追击",
	"MOTOR POOL BREACH": "突破车辆场",
	"ASSEMBLY LINE": "装配线",
	"PRESS GAUNTLET": "冲压机试炼",
	"CRUCIBLE ASCENT": "熔炉上升战",
	"BREAK THEIR REPAIR LINE": "击溃维修防线",
	"THE FLOOR IS MOVING": "地板正在移动",
	"WATCH THE WARNING FLOOR": "注意地面警告",
	"SURVIVE THE LIFT": "在升降台上活下来",
	"SHUT DOWN THE FOUNDRY": "关闭铸造厂",
	"KEEP THE EVACUATION LANE OPEN": "保持撤离通道畅通",
	"MARKET FIRELINE": "集市火线",
	"SMOKE LOCK": "烟雾封锁",
	"CISTERN APPROACH": "逼近蓄水池",
	"STRIKE BETWEEN THE FLAME CYCLES": "在火焰循环间隙发动攻击",
	"FOLLOW THE CYAN EVACUATION LIGHTS": "沿青色撤离灯前进",
	"WATER PRESSURE IS UNSTABLE": "水压并不稳定",
	"BREAK THE FIRESTORM COMMAND": "击溃火风暴指挥",
	"BREAK THROUGH THE SPORE BELT": "突破孢子带",
	"ILLEGAL MINE": "非法矿场",
	"THE QUARRY CREW IS ENTRENCHED": "采石场守军已经固守",
	"ORE-RAIL RUN": "矿轨疾驰",
	"THE GROUND IS MOVING": "地面正在移动",
	"WATCH THE LIVE CART TRACK": "注意仍在运行的矿车轨道",
	"SHUT DOWN THE DEEP-CORE DRILL": "关闭深核钻机",
	"HOLD THE DECK DURING DESCENT": "下降期间守住平台",
	"FREIGHT ELEVATOR": "货运升降梯",
	"CRYO PERIMETER": "低温区防线",
	"LASER GRID CYCLING": "激光网格正在循环",
	"COUNTERWEIGHT BREACH": "配重区突破",
	"KEEP YOUR FOOTING": "站稳脚步",
	"SEVENTH LOCK": "第七道锁",
	"BREAK THE SECURITY CORDON": "突破安保警戒线",
	"BREAK THE LOCKSTEP PROTOCOL": "击破同步协议",
	"QUARANTINE BREACH": "隔离区突破",
	"THE FINAL FACILITY IS SEALED": "最终设施已经封闭",
	"SPECIMEN CONTAINMENT": "样本收容区",
	"CLEAR THE GENE-FORGE GALLERY": "清理基因熔炉陈列馆",
	"ELITE GAUNTLET": "精英试炼",
	"FOUR PROTOCOLS // NO RETREAT": "四项协议 // 绝不后退",
	"GENESIS THRESHOLD": "创生门槛",
	"BREAK THE LAST DEFENSE LINE": "击破最后防线",
	"END THE GENESIS PROTOCOL": "终结创生协议",
}


static func text(key: String, language: String, fallback := "") -> String:
	var locale := language if UI.has(language) else "en"
	return String(UI[locale].get(key, UI.en.get(key, fallback if not fallback.is_empty() else key)))


static func dialogue(line: String, language: String) -> String:
	return String(DIALOGUE_ZH.get(line, line)) if language == "zh" else line


static func content(value: String, language: String) -> String:
	return String(CONTENT_ZH.get(value, value)) if language == "zh" else value


static func has_content_translation(value: String) -> bool:
	return CONTENT_ZH.has(value)


static func has_dialogue_translation(line: String) -> bool:
	return DIALOGUE_ZH.has(line)
