class_name ArcadeLocalization
extends RefCounted

const UI := {
	"en": {
		"title_start": "TAP / ENTER TO START",
		"title_links": "HIGH SCORES                         OPTIONS",
		"high_scores": "LOCAL HIGH SCORES",
		"return": "TAP / ENTER TO RETURN",
		"options": "OPTIONS",
		"paused_options": "PAUSED // OPTIONS",
		"resume": "ENTER / PAUSE TO RESUME",
		"option_hint": "UP/DOWN SELECT   LEFT/RIGHT CHANGE   TAP SIDES",
		"music_volume": "MUSIC VOLUME",
		"sfx_volume": "EFFECTS VOLUME",
		"touch_scale": "TOUCH SIZE",
		"touch_layout": "TOUCH LAYOUT",
		"ui_scale": "UI SIZE",
		"screen_shake": "SCREEN SHAKE",
		"hit_flash": "HIT FLASH",
		"haptics": "HAPTICS",
		"high_contrast_cues": "HIGH-CONTRAST CUES",
		"subtitles": "SUBTITLES",
		"language": "LANGUAGE",
		"controls": "REMAP CONTROLS",
		"controls_title": "REMAP CONTROLS",
		"open": "OPEN  >",
		"score_columns": "RANK   OPERATIVE       SCORE       STAGE / TEAM",
		"rebind_hint": "ATTACK TO REBIND     ESC CANCELS CAPTURE",
		"press_key": "PRESS A KEY...",
		"move_left": "MOVE LEFT",
		"move_right": "MOVE RIGHT",
		"move_up": "MOVE UP",
		"move_down": "MOVE DOWN",
		"attack": "ATTACK",
		"jump": "JUMP",
		"special": "SPECIAL",
		"pause": "PAUSE",
		"continue": "CONTINUE?",
		"continue_hint": "ATTACK / START TO CONTINUE",
		"game_over": "GAME OVER",
		"final_score": "FINAL SCORE",
		"on": "ON",
		"off": "OFF",
		"layout_classic": "CLASSIC",
		"layout_compact": "COMPACT",
		"layout_left_handed": "LEFT HANDED",
	},
	"zh": {
		"title_start": "点击 / 回车 开始",
		"title_links": "高分榜                              设置",
		"high_scores": "本地高分榜",
		"return": "点击 / 回车 返回",
		"options": "设置",
		"paused_options": "暂停 // 设置",
		"resume": "回车 / 暂停键 继续",
		"option_hint": "上下选择   左右调整   触屏点击两侧",
		"music_volume": "音乐音量",
		"sfx_volume": "音效音量",
		"touch_scale": "触控尺寸",
		"touch_layout": "触控布局",
		"ui_scale": "界面字号",
		"screen_shake": "画面震动",
		"hit_flash": "受击闪光",
		"haptics": "触觉反馈",
		"high_contrast_cues": "高对比度警告",
		"subtitles": "字幕",
		"language": "语言",
		"controls": "按键重绑定",
		"controls_title": "按键重绑定",
		"open": "打开  >",
		"score_columns": "排名   角色             得分        关卡 / 队伍",
		"rebind_hint": "按攻击键重绑定     ESC 取消输入",
		"press_key": "请按一个按键...",
		"move_left": "向左移动",
		"move_right": "向右移动",
		"move_up": "向上移动",
		"move_down": "向下移动",
		"attack": "攻击",
		"jump": "跳跃",
		"special": "必杀技",
		"pause": "暂停",
		"continue": "是否续关？",
		"continue_hint": "攻击 / 开始键 确认续关",
		"game_over": "游戏结束",
		"final_score": "最终得分",
		"on": "开启",
		"off": "关闭",
		"layout_classic": "经典",
		"layout_compact": "紧凑",
		"layout_left_handed": "左手",
	},
}

const DIALOGUE_ZH := {
	"This district answers to me.": "这片街区由我说了算。",
	"No more warnings. Overdrive!": "警告结束。超载启动！",
	"The flood keeps what it takes.": "洪水夺走的，从不归还。",
	"Then run against the current!": "那就逆着激流逃吧！",
	"Everything breaks in the deluge!": "洪流之中，一切都会粉碎！",
	"This road belongs to the convoy.": "这条路属于我们的车队。",
	"Watch the asphalt burn.": "看着柏油路燃烧吧。",
	"Redline. No brakes.": "转速拉满。绝不刹车。",
	"Every road ends in my furnace.": "每一条路最终都通向我的熔炉。",
	"Steel answers when I call.": "钢铁会回应我的召唤。",
	"Overdrive. Melt with the rest!": "超载启动。和他们一起熔化吧！",
	"The refuge burns by my command.": "避难所因我的命令而燃烧。",
	"Then face what survived the furnace.": "那就面对从熔炉中活下来的东西。",
	"Ash and water. Drown in both!": "灰烬与洪水——溺死其中吧！",
	"This quarry was old before your species learned fear.": "在你们的种族懂得恐惧前，这座矿场就已存在。",
	"Wake, old giant. Clear the shaft.": "醒来吧，古老巨兽。清空矿井。",
	"Then I drill through you myself!": "那我就亲自把你钻穿！",
	"The lower archive remains sealed.": "下层档案库必须继续封锁。",
	"Nyx. Lockstep pattern. No gaps.": "妮克斯，同步阵型，不留缺口。",
	"You crossed six locks to die at the seventh.": "你穿过六道锁，只为死在第七道。",
	"Crossfire live. Close every lane.": "交叉火力启动。封死所有通道。",
	"You crossed seven locks to witness a new world.": "你穿过七道锁，只为见证新世界。",
	"Then survive the shape it demands.": "那就从它要求的形态中活下来。",
	"No vessel. No limit. No retreat.": "无须容器。没有极限。绝不后退。",
}


static func text(key: String, language: String, fallback := "") -> String:
	var locale := language if UI.has(language) else "en"
	return String(UI[locale].get(key, UI.en.get(key, fallback if not fallback.is_empty() else key)))


static func dialogue(line: String, language: String) -> String:
	return String(DIALOGUE_ZH.get(line, line)) if language == "zh" else line


static func has_dialogue_translation(line: String) -> bool:
	return DIALOGUE_ZH.has(line)
